import Link from "next/link";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { 
  Globe, 
  Zap, 
  Trophy, 
  Brain, 
  Target, 
  Rocket,
  ChevronRight,
  Building2,
  GraduationCap,
  Award,
  Users,
  Play
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { UserNav } from "@/components/user-nav";

const features = [
  {
    icon: Globe,
    title: "Real-World Locations",
    description: "Click on actual businesses worldwide. JP Morgan, NHS, Tesla - solve their cloud challenges.",
    color: "text-cyan-400",
    bgColor: "bg-cyan-400/10",
  },
  {
    icon: Brain,
    title: "AI-Powered Scenarios",
    description: "Dynamic challenges generated by AI based on real industry requirements and compliance needs.",
    color: "text-purple-400",
    bgColor: "bg-purple-400/10",
  },
  {
    icon: Target,
    title: "Build Real Architectures",
    description: "Design actual AWS/GCP/Azure architectures. Not cartoons - deployable infrastructure.",
    color: "text-amber-400",
    bgColor: "bg-amber-400/10",
  },
  {
    icon: Zap,
    title: "Instant Feedback",
    description: "AI grades your solutions on security, cost, performance, and best practices.",
    color: "text-green-400",
    bgColor: "bg-green-400/10",
  },
];

const stats = [
  { value: "500+", label: "Real Companies", icon: Building2 },
  { value: "12", label: "Industry Sectors", icon: GraduationCap },
  { value: "50+", label: "AWS Services", icon: Award },
  { value: "10K+", label: "Architects Trained", icon: Users },
];

const industries = [
  { name: "Banking & Finance", icon: "🏦", challenges: 45 },
  { name: "Healthcare", icon: "🏥", challenges: 38 },
  { name: "E-Commerce", icon: "🛒", challenges: 52 },
  { name: "Gaming", icon: "🎮", challenges: 31 },
  { name: "Media & Streaming", icon: "📺", challenges: 28 },
  { name: "Logistics", icon: "🚚", challenges: 35 },
];

export default async function Home() {
  const session = await getServerSession(authOptions);
  
  return (
    <div className="min-h-screen bg-background">
      {/* Navigation */}
      <nav className="fixed top-0 left-0 right-0 z-50 border-b border-border/50 bg-background/80 backdrop-blur-xl">
        <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-cyan-400 to-blue-500 flex items-center justify-center">
              <Globe className="w-6 h-6 text-white" />
            </div>
            <span className="text-xl font-bold">CloudAcademy</span>
          </div>
          <div className="hidden md:flex items-center gap-8">
            <Link href="/world" className="text-muted-foreground hover:text-foreground transition-colors">
              World Map
            </Link>
            <Link href="/challenges" className="text-muted-foreground hover:text-foreground transition-colors">
              Challenges
            </Link>
            <Link href="/leaderboard" className="text-muted-foreground hover:text-foreground transition-colors">
              Leaderboard
            </Link>
            <Link href="/pricing" className="text-muted-foreground hover:text-foreground transition-colors">
              Pricing
            </Link>
          </div>
          <div className="flex items-center gap-3">
            <UserNav user={session?.user ? { username: session.user.username, subscriptionTier: session.user.subscriptionTier } : null} />
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="pt-32 pb-20 px-6 relative overflow-hidden">
        {/* Background Effects */}
        <div className="absolute inset-0 bg-globe-gradient opacity-50" />
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[800px] rounded-full bg-gradient-radial from-cyan-500/10 via-transparent to-transparent blur-3xl" />
        
        <div className="max-w-7xl mx-auto relative">
          <div className="text-center max-w-4xl mx-auto">
            {/* Badge */}
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-cyan-500/10 border border-cyan-500/20 text-cyan-400 text-sm font-medium mb-8">
              <Rocket className="w-4 h-4" />
              The Future of Cloud Training
            </div>
            
            {/* Main Headline */}
            <h1 className="text-5xl md:text-7xl font-extrabold tracking-tight mb-6">
              <span className="bg-gradient-to-r from-white via-white to-white/60 bg-clip-text text-transparent">
                Master Cloud Architecture
              </span>
              <br />
              <span className="bg-gradient-to-r from-cyan-400 to-blue-500 bg-clip-text text-transparent">
                Through Real-World Missions
              </span>
            </h1>
            
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto mb-10">
              Fly around the globe. Click on real companies. Solve their cloud challenges. 
              Build architectures that actually deploy. This is{" "}
              <span className="text-cyan-400 font-semibold">Microsoft Flight Simulator</span> for Solutions Architects.
            </p>
            
            {/* CTA Buttons */}
            <div className="flex flex-col sm:flex-row items-center justify-center gap-4 mb-16">
              <Link href="/world">
                <Button variant="glow" size="xl" className="gap-2 group">
                  <Play className="w-5 h-5" />
                  Enter World Map
                  <ChevronRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
                </Button>
              </Link>
              <Button variant="outline" size="xl" className="gap-2">
                <Trophy className="w-5 h-5 text-amber-400" />
                View Leaderboard
              </Button>
            </div>
            
            {/* Stats */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-6 max-w-3xl mx-auto">
              {stats.map((stat) => (
                <div key={stat.label} className="text-center">
                  <div className="text-3xl font-bold text-foreground mb-1">{stat.value}</div>
                  <div className="text-sm text-muted-foreground">{stat.label}</div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Globe Preview Section */}
      <section className="py-20 px-6 relative">
        <div className="max-w-7xl mx-auto">
          <div className="relative rounded-3xl overflow-hidden border border-border/50 bg-card/50 backdrop-blur-sm">
            {/* Fake Globe Preview - will be replaced with actual globe */}
            <div className="aspect-[16/9] bg-gradient-to-b from-slate-900 to-slate-950 relative flex items-center justify-center">
              <div className="absolute inset-0 bg-[url('/grid.svg')] opacity-20" />
              <div className="w-[400px] h-[400px] rounded-full bg-gradient-to-br from-cyan-500/20 to-blue-600/20 border border-cyan-500/30 globe-glow flex items-center justify-center">
                <Globe className="w-32 h-32 text-cyan-400/50" />
              </div>
              {/* Floating markers */}
              <div className="absolute top-1/4 left-1/4 w-4 h-4 rounded-full bg-cyan-400 animate-pulse shadow-lg shadow-cyan-400/50" />
              <div className="absolute top-1/3 right-1/3 w-4 h-4 rounded-full bg-amber-400 animate-pulse shadow-lg shadow-amber-400/50" />
              <div className="absolute bottom-1/3 left-1/3 w-4 h-4 rounded-full bg-green-400 animate-pulse shadow-lg shadow-green-400/50" />
              <div className="absolute bottom-1/4 right-1/4 w-4 h-4 rounded-full bg-purple-400 animate-pulse shadow-lg shadow-purple-400/50" />
              
              {/* Overlay text */}
              <div className="absolute inset-0 flex items-center justify-center bg-black/40">
                <div className="text-center">
                  <p className="text-2xl font-bold text-white mb-4">Interactive 3D Globe</p>
                  <Link href="/world">
                    <Button variant="glow" size="lg" className="gap-2">
                      <Globe className="w-5 h-5" />
                      Launch World Map
                    </Button>
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 px-6">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold mb-4">
              Not Your Average Cloud Training
            </h2>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
              Forget static tutorials and cartoon games. This is enterprise-grade simulation.
            </p>
          </div>
          
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
            {features.map((feature) => (
              <Card key={feature.title} className="bg-card/50 border-border/50 hover:border-primary/50 transition-colors">
                <CardContent className="pt-6">
                  <div className={`w-12 h-12 rounded-xl ${feature.bgColor} flex items-center justify-center mb-4`}>
                    <feature.icon className={`w-6 h-6 ${feature.color}`} />
                  </div>
                  <h3 className="text-lg font-semibold mb-2">{feature.title}</h3>
                  <p className="text-sm text-muted-foreground">{feature.description}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Industries Section */}
      <section className="py-20 px-6 bg-card/30">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold mb-4">
              Train Across Every Industry
            </h2>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
              Each sector has unique compliance, scale, and architecture requirements.
            </p>
          </div>
          
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
            {industries.map((industry) => (
              <Card key={industry.name} className="bg-card/50 border-border/50 hover:border-primary/50 transition-all hover:scale-[1.02] cursor-pointer group">
                <CardContent className="p-6 flex items-center gap-4">
                  <div className="text-4xl">{industry.icon}</div>
                  <div className="flex-1">
                    <h3 className="font-semibold group-hover:text-primary transition-colors">{industry.name}</h3>
                    <p className="text-sm text-muted-foreground">{industry.challenges} challenges</p>
                  </div>
                  <ChevronRight className="w-5 h-5 text-muted-foreground group-hover:text-primary group-hover:translate-x-1 transition-all" />
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 px-6">
        <div className="max-w-4xl mx-auto text-center">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-amber-500/10 border border-amber-500/20 text-amber-400 text-sm font-medium mb-8">
            <Trophy className="w-4 h-4" />
            Join 10,000+ Cloud Architects
          </div>
          <h2 className="text-4xl md:text-5xl font-bold mb-6">
            Ready to Become a{" "}
            <span className="bg-gradient-to-r from-cyan-400 to-blue-500 bg-clip-text text-transparent">
              World-Class Architect?
            </span>
          </h2>
          <p className="text-xl text-muted-foreground mb-10 max-w-2xl mx-auto">
            Start your journey today. Explore the globe, tackle real challenges, and build the skills that matter.
          </p>
          <Link href="/world">
            <Button variant="glow" size="xl" className="gap-2">
              <Globe className="w-5 h-5" />
              Start Your Mission
            </Button>
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-border/50 py-12 px-6">
        <div className="max-w-7xl mx-auto flex flex-col md:flex-row items-center justify-between gap-6">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-cyan-400 to-blue-500 flex items-center justify-center">
              <Globe className="w-5 h-5 text-white" />
            </div>
            <span className="font-bold">CloudAcademy</span>
          </div>
          <p className="text-sm text-muted-foreground">
            Part of the CloudFabric ecosystem. © 2024 All rights reserved.
          </p>
          <div className="flex items-center gap-6 text-sm text-muted-foreground">
            <Link href="/privacy" className="hover:text-foreground transition-colors">Privacy</Link>
            <Link href="/terms" className="hover:text-foreground transition-colors">Terms</Link>
            <Link href="/contact" className="hover:text-foreground transition-colors">Contact</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
