/**
 * Generate a sample CloudFormation template for AWS CLI validation
 * Run: npx tsx scripts/generate-sample-template.ts
 * Then: aws cloudformation validate-template --template-body file://sample-template.json
 */

import * as fs from "fs";
import * as path from "path";

// Sample CloudFormation template matching our generator output
const sampleTemplate = {
  AWSTemplateFormatVersion: "2010-09-09",
  Description: "Sample CloudFormation template for validation - Generated by CloudMigrate",
  Resources: {
    // VPC
    MainVPC: {
      Type: "AWS::EC2::VPC",
      Properties: {
        CidrBlock: "10.0.0.0/16",
        EnableDnsHostnames: true,
        EnableDnsSupport: true,
        Tags: [{ Key: "Name", Value: "MainVPC" }],
      },
    },
    
    // Public Subnet
    PublicSubnet: {
      Type: "AWS::EC2::Subnet",
      Properties: {
        VpcId: { Ref: "MainVPC" },
        CidrBlock: "10.0.1.0/24",
        AvailabilityZone: { "Fn::Select": [0, { "Fn::GetAZs": "" }] },
        MapPublicIpOnLaunch: true,
        Tags: [{ Key: "Name", Value: "PublicSubnet" }],
      },
      DependsOn: ["MainVPC"],
    },
    
    // Private Subnet
    PrivateSubnet: {
      Type: "AWS::EC2::Subnet",
      Properties: {
        VpcId: { Ref: "MainVPC" },
        CidrBlock: "10.0.2.0/24",
        AvailabilityZone: { "Fn::Select": [1, { "Fn::GetAZs": "" }] },
        MapPublicIpOnLaunch: false,
        Tags: [{ Key: "Name", Value: "PrivateSubnet" }],
      },
      DependsOn: ["MainVPC"],
    },
    
    // Internet Gateway
    InternetGateway: {
      Type: "AWS::EC2::InternetGateway",
      Properties: {
        Tags: [{ Key: "Name", Value: "MainIGW" }],
      },
    },
    
    // Security Group
    WebSecurityGroup: {
      Type: "AWS::EC2::SecurityGroup",
      Properties: {
        GroupDescription: "Security group for web servers",
        VpcId: { Ref: "MainVPC" },
        SecurityGroupIngress: [
          { IpProtocol: "tcp", FromPort: 443, ToPort: 443, CidrIp: "0.0.0.0/0" },
          { IpProtocol: "tcp", FromPort: 80, ToPort: 80, CidrIp: "0.0.0.0/0" },
        ],
        Tags: [{ Key: "Name", Value: "WebSecurityGroup" }],
      },
      DependsOn: ["MainVPC"],
    },
    
    // EC2 Instance
    WebServer: {
      Type: "AWS::EC2::Instance",
      Properties: {
        InstanceType: "t3.micro",
        ImageId: { Ref: "LatestAmiId" },
        SubnetId: { Ref: "PublicSubnet" },
        SecurityGroupIds: [{ Ref: "WebSecurityGroup" }],
        Tags: [{ Key: "Name", Value: "WebServer" }],
      },
      DependsOn: ["PublicSubnet", "WebSecurityGroup"],
    },
    
    // S3 Bucket
    StaticAssetsBucket: {
      Type: "AWS::S3::Bucket",
      Properties: {
        VersioningConfiguration: { Status: "Enabled" },
        PublicAccessBlockConfiguration: {
          BlockPublicAcls: true,
          BlockPublicPolicy: true,
          IgnorePublicAcls: true,
          RestrictPublicBuckets: true,
        },
        BucketEncryption: {
          ServerSideEncryptionConfiguration: [{
            ServerSideEncryptionByDefault: {
              SSEAlgorithm: "AES256",
            },
          }],
        },
        Tags: [{ Key: "Name", Value: "StaticAssets" }],
      },
    },
    
    // Lambda Execution Role
    LambdaExecutionRole: {
      Type: "AWS::IAM::Role",
      Properties: {
        AssumeRolePolicyDocument: {
          Version: "2012-10-17",
          Statement: [{
            Effect: "Allow",
            Principal: { Service: "lambda.amazonaws.com" },
            Action: "sts:AssumeRole",
          }],
        },
        ManagedPolicyArns: [
          "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole",
        ],
        Tags: [{ Key: "Name", Value: "LambdaExecutionRole" }],
      },
    },
    
    // Lambda Function
    ApiHandler: {
      Type: "AWS::Lambda::Function",
      Properties: {
        Runtime: "nodejs20.x",
        Handler: "index.handler",
        Role: { "Fn::GetAtt": ["LambdaExecutionRole", "Arn"] },
        MemorySize: 128,
        Timeout: 30,
        Code: {
          ZipFile: "exports.handler = async (event) => ({ statusCode: 200, body: JSON.stringify({ message: 'Hello' }) });",
        },
        Tags: [{ Key: "Name", Value: "ApiHandler" }],
      },
      DependsOn: ["LambdaExecutionRole"],
    },
    
    // DynamoDB Table
    DataTable: {
      Type: "AWS::DynamoDB::Table",
      Properties: {
        BillingMode: "PAY_PER_REQUEST",
        AttributeDefinitions: [
          { AttributeName: "id", AttributeType: "S" },
        ],
        KeySchema: [
          { AttributeName: "id", KeyType: "HASH" },
        ],
        Tags: [{ Key: "Name", Value: "DataTable" }],
      },
    },
    
    // SNS Topic
    NotificationTopic: {
      Type: "AWS::SNS::Topic",
      Properties: {
        TopicName: "Notifications",
        Tags: [{ Key: "Name", Value: "NotificationTopic" }],
      },
    },
    
    // SQS Queue
    TaskQueue: {
      Type: "AWS::SQS::Queue",
      Properties: {
        QueueName: "TaskQueue",
        VisibilityTimeout: 30,
        Tags: [{ Key: "Name", Value: "TaskQueue" }],
      },
    },
  },
  
  Parameters: {
    LatestAmiId: {
      Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>",
      Default: "/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64",
      Description: "Latest Amazon Linux 2023 AMI ID",
    },
  },
  
  Outputs: {
    VpcId: {
      Description: "VPC ID",
      Value: { Ref: "MainVPC" },
      Export: { Name: "MainVPC-Id" },
    },
    BucketName: {
      Description: "S3 Bucket Name",
      Value: { Ref: "StaticAssetsBucket" },
    },
    LambdaArn: {
      Description: "Lambda Function ARN",
      Value: { "Fn::GetAtt": ["ApiHandler", "Arn"] },
    },
  },
};

// Write to file
const outputPath = path.join(process.cwd(), "sample-template.json");
fs.writeFileSync(outputPath, JSON.stringify(sampleTemplate, null, 2));

console.log(`✅ Sample CloudFormation template generated: ${outputPath}`);
console.log(`\nTo validate with AWS CLI:`);
console.log(`  aws cloudformation validate-template --template-body file://sample-template.json`);
console.log(`\nTo create a stack (requires AWS credentials):`);
console.log(`  aws cloudformation create-stack --stack-name test-stack --template-body file://sample-template.json --capabilities CAPABILITY_IAM`);
